In [2]:
import pandas as pd

products = [135, 45, 64, 280, 70]

hdict = []

for p in products:
    for i in range(10):
        for j in range(10):
            for k in range(10):
                product = i*j*k
                # print("The product of {}*{}*{} = {}".format(i, j, k, product))
                if product == p:
                    print("The product of {}*{}*{} = {} and product = {}".format(i, j, k, product, p))
                    h = {'i':i, 'j':j, 'k':k, 'product':product, 'p':p}
                    hdict.append(h)

hdf = pd.DataFrame(hdict, columns=['i','j','k','product','p'])
hdf.head()

The product of 3*5*9 = 135 and product = 135
The product of 3*9*5 = 135 and product = 135
The product of 5*3*9 = 135 and product = 135
The product of 5*9*3 = 135 and product = 135
The product of 9*3*5 = 135 and product = 135
The product of 9*5*3 = 135 and product = 135
The product of 1*5*9 = 45 and product = 45
The product of 1*9*5 = 45 and product = 45
The product of 3*3*5 = 45 and product = 45
The product of 3*5*3 = 45 and product = 45
The product of 5*1*9 = 45 and product = 45
The product of 5*3*3 = 45 and product = 45
The product of 5*9*1 = 45 and product = 45
The product of 9*1*5 = 45 and product = 45
The product of 9*5*1 = 45 and product = 45
The product of 1*8*8 = 64 and product = 64
The product of 2*4*8 = 64 and product = 64
The product of 2*8*4 = 64 and product = 64
The product of 4*2*8 = 64 and product = 64
The product of 4*4*4 = 64 and product = 64
The product of 4*8*2 = 64 and product = 64
The product of 8*1*8 = 64 and product = 64
The product of 8*2*4 = 64 and product = 64
The product of 8*4*2 = 64 and product = 64
The product of 8*8*1 = 64 and product = 64
The product of 5*7*8 = 280 and product = 280
The product of 5*8*7 = 280 and product = 280
The product of 7*5*8 = 280 and product = 280
The product of 7*8*5 = 280 and product = 280
The product of 8*5*7 = 280 and product = 280
The product of 8*7*5 = 280 and product = 280
The product of 2*5*7 = 70 and product = 70
The product of 2*7*5 = 70 and product = 70
The product of 5*2*7 = 70 and product = 70
The product of 5*7*2 = 70 and product = 70
The product of 7*2*5 = 70 and product = 70
The product of 7*5*2 = 70 and product = 70

   i  j  k  product    p
0  3  5  9      135  135
1  3  9  5      135  135
2  5  3  9      135  135
3  5  9  3      135  135
4  9  3  5      135  135

In [5]:
products = [3000, 3969, 640]

vdict = []

for p in products:
    for a in range(10):
        for b in range(10):
            for c in range(10):
                for d in range(10):
                    for e in range(10):
                        product = a*b*c*d*e
                        # print("The product of {}*{}*{} = {}".format(i, j, k, product))
                        if product == p:
                            solution = "{}*{}*{}*{}*{}".format(a, b, c, d, e)
                            print("The product of {}*{}*{}*{}*{} = {} and product = {}".format(a, b, c, d, e, product, p))
                            v = {'a':a, 'b':b, 'c':c, 'd':d, 'e':e, 'product':product, 'p':p}
                            vdict.append(v)

vdf = pd.DataFrame(vdict, columns=['a','b','c','d','e','product','p'])
vdf.head()

The product of 3*5*5*5*8 = 3000 and product = 3000
The product of 3*5*5*8*5 = 3000 and product = 3000
The product of 3*5*8*5*5 = 3000 and product = 3000
The product of 3*8*5*5*5 = 3000 and product = 3000
The product of 4*5*5*5*6 = 3000 and product = 3000
The product of 4*5*5*6*5 = 3000 and product = 3000
The product of 4*5*6*5*5 = 3000 and product = 3000
The product of 4*6*5*5*5 = 3000 and product = 3000
The product of 5*3*5*5*8 = 3000 and product = 3000
The product of 5*3*5*8*5 = 3000 and product = 3000
The product of 5*3*8*5*5 = 3000 and product = 3000
The product of 5*4*5*5*6 = 3000 and product = 3000
The product of 5*4*5*6*5 = 3000 and product = 3000
The product of 5*4*6*5*5 = 3000 and product = 3000
The product of 5*5*3*5*8 = 3000 and product = 3000
The product of 5*5*3*8*5 = 3000 and product = 3000
The product of 5*5*4*5*6 = 3000 and product = 3000
The product of 5*5*4*6*5 = 3000 and product = 3000
The product of 5*5*5*3*8 = 3000 and product = 3000
The product of 5*5*5*4*6 = 3000 and product = 3000
The product of 5*5*5*6*4 = 3000 and product = 3000
The product of 5*5*5*8*3 = 3000 and product = 3000
The product of 5*5*6*4*5 = 3000 and product = 3000
The product of 5*5*6*5*4 = 3000 and product = 3000
The product of 5*5*8*3*5 = 3000 and product = 3000
The product of 5*5*8*5*3 = 3000 and product = 3000
The product of 5*6*4*5*5 = 3000 and product = 3000
The product of 5*6*5*4*5 = 3000 and product = 3000
The product of 5*6*5*5*4 = 3000 and product = 3000
The product of 5*8*3*5*5 = 3000 and product = 3000
The product of 5*8*5*3*5 = 3000 and product = 3000
The product of 5*8*5*5*3 = 3000 and product = 3000
The product of 6*4*5*5*5 = 3000 and product = 3000
The product of 6*5*4*5*5 = 3000 and product = 3000
The product of 6*5*5*4*5 = 3000 and product = 3000
The product of 6*5*5*5*4 = 3000 and product = 3000
The product of 8*3*5*5*5 = 3000 and product = 3000
The product of 8*5*3*5*5 = 3000 and product = 3000
The product of 8*5*5*3*5 = 3000 and product = 3000
The product of 8*5*5*5*3 = 3000 and product = 3000
The product of 1*7*7*9*9 = 3969 and product = 3969
The product of 1*7*9*7*9 = 3969 and product = 3969
The product of 1*7*9*9*7 = 3969 and product = 3969
The product of 1*9*7*7*9 = 3969 and product = 3969
The product of 1*9*7*9*7 = 3969 and product = 3969
The product of 1*9*9*7*7 = 3969 and product = 3969
The product of 3*3*7*7*9 = 3969 and product = 3969
The product of 3*3*7*9*7 = 3969 and product = 3969
The product of 3*3*9*7*7 = 3969 and product = 3969
The product of 3*7*3*7*9 = 3969 and product = 3969
The product of 3*7*3*9*7 = 3969 and product = 3969
The product of 3*7*7*3*9 = 3969 and product = 3969
The product of 3*7*7*9*3 = 3969 and product = 3969
The product of 3*7*9*3*7 = 3969 and product = 3969
The product of 3*7*9*7*3 = 3969 and product = 3969
The product of 3*9*3*7*7 = 3969 and product = 3969
The product of 3*9*7*3*7 = 3969 and product = 3969
The product of 3*9*7*7*3 = 3969 and product = 3969
The product of 7*1*7*9*9 = 3969 and product = 3969
The product of 7*1*9*7*9 = 3969 and product = 3969
The product of 7*1*9*9*7 = 3969 and product = 3969
The product of 7*3*3*7*9 = 3969 and product = 3969
The product of 7*3*3*9*7 = 3969 and product = 3969
The product of 7*3*7*3*9 = 3969 and product = 3969
The product of 7*3*7*9*3 = 3969 and product = 3969
The product of 7*3*9*3*7 = 3969 and product = 3969
The product of 7*3*9*7*3 = 3969 and product = 3969
The product of 7*7*1*9*9 = 3969 and product = 3969
The product of 7*7*3*3*9 = 3969 and product = 3969
The product of 7*7*3*9*3 = 3969 and product = 3969
The product of 7*7*9*1*9 = 3969 and product = 3969
The product of 7*7*9*3*3 = 3969 and product = 3969
The product of 7*7*9*9*1 = 3969 and product = 3969
The product of 7*9*1*7*9 = 3969 and product = 3969
The product of 7*9*1*9*7 = 3969 and product = 3969
The product of 7*9*3*3*7 = 3969 and product = 3969
The product of 7*9*3*7*3 = 3969 and product = 3969
The product of 7*9*7*1*9 = 3969 and product = 3969
The product of 7*9*7*3*3 = 3969 and product = 3969
The product of 7*9*7*9*1 = 3969 and product = 3969
The product of 7*9*9*1*7 = 3969 and product = 3969
The product of 7*9*9*7*1 = 3969 and product = 3969
The product of 9*1*7*7*9 = 3969 and product = 3969
The product of 9*1*7*9*7 = 3969 and product = 3969
The product of 9*1*9*7*7 = 3969 and product = 3969
The product of 9*3*3*7*7 = 3969 and product = 3969
The product of 9*3*7*3*7 = 3969 and product = 3969
The product of 9*3*7*7*3 = 3969 and product = 3969
The product of 9*7*1*7*9 = 3969 and product = 3969
The product of 9*7*1*9*7 = 3969 and product = 3969
The product of 9*7*3*3*7 = 3969 and product = 3969
The product of 9*7*3*7*3 = 3969 and product = 3969
The product of 9*7*7*1*9 = 3969 and product = 3969
The product of 9*7*7*3*3 = 3969 and product = 3969
The product of 9*7*7*9*1 = 3969 and product = 3969
The product of 9*7*9*1*7 = 3969 and product = 3969
The product of 9*7*9*7*1 = 3969 and product = 3969
The product of 9*9*1*7*7 = 3969 and product = 3969
The product of 9*9*7*1*7 = 3969 and product = 3969
The product of 9*9*7*7*1 = 3969 and product = 3969
The product of 1*2*5*8*8 = 640 and product = 640
The product of 1*2*8*5*8 = 640 and product = 640
The product of 1*2*8*8*5 = 640 and product = 640
The product of 1*4*4*5*8 = 640 and product = 640
The product of 1*4*4*8*5 = 640 and product = 640
The product of 1*4*5*4*8 = 640 and product = 640
The product of 1*4*5*8*4 = 640 and product = 640
The product of 1*4*8*4*5 = 640 and product = 640
The product of 1*4*8*5*4 = 640 and product = 640
The product of 1*5*2*8*8 = 640 and product = 640
The product of 1*5*4*4*8 = 640 and product = 640
The product of 1*5*4*8*4 = 640 and product = 640
The product of 1*5*8*2*8 = 640 and product = 640
The product of 1*5*8*4*4 = 640 and product = 640
The product of 1*5*8*8*2 = 640 and product = 640
The product of 1*8*2*5*8 = 640 and product = 640
The product of 1*8*2*8*5 = 640 and product = 640
The product of 1*8*4*4*5 = 640 and product = 640
The product of 1*8*4*5*4 = 640 and product = 640
The product of 1*8*5*2*8 = 640 and product = 640
The product of 1*8*5*4*4 = 640 and product = 640
The product of 1*8*5*8*2 = 640 and product = 640
The product of 1*8*8*2*5 = 640 and product = 640
The product of 1*8*8*5*2 = 640 and product = 640
The product of 2*1*5*8*8 = 640 and product = 640
The product of 2*1*8*5*8 = 640 and product = 640
The product of 2*1*8*8*5 = 640 and product = 640
The product of 2*2*4*5*8 = 640 and product = 640
The product of 2*2*4*8*5 = 640 and product = 640
The product of 2*2*5*4*8 = 640 and product = 640
The product of 2*2*5*8*4 = 640 and product = 640
The product of 2*2*8*4*5 = 640 and product = 640
The product of 2*2*8*5*4 = 640 and product = 640
The product of 2*4*2*5*8 = 640 and product = 640
The product of 2*4*2*8*5 = 640 and product = 640
The product of 2*4*4*4*5 = 640 and product = 640
The product of 2*4*4*5*4 = 640 and product = 640
The product of 2*4*5*2*8 = 640 and product = 640
The product of 2*4*5*4*4 = 640 and product = 640
The product of 2*4*5*8*2 = 640 and product = 640
The product of 2*4*8*2*5 = 640 and product = 640
The product of 2*4*8*5*2 = 640 and product = 640
The product of 2*5*1*8*8 = 640 and product = 640
The product of 2*5*2*4*8 = 640 and product = 640
The product of 2*5*2*8*4 = 640 and product = 640
The product of 2*5*4*2*8 = 640 and product = 640
The product of 2*5*4*4*4 = 640 and product = 640
The product of 2*5*4*8*2 = 640 and product = 640
The product of 2*5*8*1*8 = 640 and product = 640
The product of 2*5*8*2*4 = 640 and product = 640
The product of 2*5*8*4*2 = 640 and product = 640
The product of 2*5*8*8*1 = 640 and product = 640
The product of 2*8*1*5*8 = 640 and product = 640
The product of 2*8*1*8*5 = 640 and product = 640
The product of 2*8*2*4*5 = 640 and product = 640
The product of 2*8*2*5*4 = 640 and product = 640
The product of 2*8*4*2*5 = 640 and product = 640
The product of 2*8*4*5*2 = 640 and product = 640
The product of 2*8*5*1*8 = 640 and product = 640
The product of 2*8*5*2*4 = 640 and product = 640
The product of 2*8*5*4*2 = 640 and product = 640
The product of 2*8*5*8*1 = 640 and product = 640
The product of 2*8*8*1*5 = 640 and product = 640
The product of 2*8*8*5*1 = 640 and product = 640
The product of 4*1*4*5*8 = 640 and product = 640
The product of 4*1*4*8*5 = 640 and product = 640
The product of 4*1*5*4*8 = 640 and product = 640
The product of 4*1*5*8*4 = 640 and product = 640
The product of 4*1*8*4*5 = 640 and product = 640
The product of 4*1*8*5*4 = 640 and product = 640
The product of 4*2*2*5*8 = 640 and product = 640
The product of 4*2*2*8*5 = 640 and product = 640
The product of 4*2*4*4*5 = 640 and product = 640
The product of 4*2*4*5*4 = 640 and product = 640
The product of 4*2*5*2*8 = 640 and product = 640
The product of 4*2*5*4*4 = 640 and product = 640
The product of 4*2*5*8*2 = 640 and product = 640
The product of 4*2*8*2*5 = 640 and product = 640
The product of 4*2*8*5*2 = 640 and product = 640
The product of 4*4*1*5*8 = 640 and product = 640
The product of 4*4*1*8*5 = 640 and product = 640
The product of 4*4*2*4*5 = 640 and product = 640
The product of 4*4*2*5*4 = 640 and product = 640
The product of 4*4*4*2*5 = 640 and product = 640
The product of 4*4*4*5*2 = 640 and product = 640
The product of 4*4*5*1*8 = 640 and product = 640
The product of 4*4*5*2*4 = 640 and product = 640
The product of 4*4*5*4*2 = 640 and product = 640
The product of 4*4*5*8*1 = 640 and product = 640
The product of 4*4*8*1*5 = 640 and product = 640
The product of 4*4*8*5*1 = 640 and product = 640
The product of 4*5*1*4*8 = 640 and product = 640
The product of 4*5*1*8*4 = 640 and product = 640
The product of 4*5*2*2*8 = 640 and product = 640
The product of 4*5*2*4*4 = 640 and product = 640
The product of 4*5*2*8*2 = 640 and product = 640
The product of 4*5*4*1*8 = 640 and product = 640
The product of 4*5*4*2*4 = 640 and product = 640
The product of 4*5*4*4*2 = 640 and product = 640
The product of 4*5*4*8*1 = 640 and product = 640
The product of 4*5*8*1*4 = 640 and product = 640
The product of 4*5*8*2*2 = 640 and product = 640
The product of 4*5*8*4*1 = 640 and product = 640
The product of 4*8*1*4*5 = 640 and product = 640
The product of 4*8*1*5*4 = 640 and product = 640
The product of 4*8*2*2*5 = 640 and product = 640
The product of 4*8*2*5*2 = 640 and product = 640
The product of 4*8*4*1*5 = 640 and product = 640
The product of 4*8*4*5*1 = 640 and product = 640
The product of 4*8*5*1*4 = 640 and product = 640
The product of 4*8*5*2*2 = 640 and product = 640
The product of 4*8*5*4*1 = 640 and product = 640
The product of 5*1*2*8*8 = 640 and product = 640
The product of 5*1*4*4*8 = 640 and product = 640
The product of 5*1*4*8*4 = 640 and product = 640
The product of 5*1*8*2*8 = 640 and product = 640
The product of 5*1*8*4*4 = 640 and product = 640
The product of 5*1*8*8*2 = 640 and product = 640
The product of 5*2*1*8*8 = 640 and product = 640
The product of 5*2*2*4*8 = 640 and product = 640
The product of 5*2*2*8*4 = 640 and product = 640
The product of 5*2*4*2*8 = 640 and product = 640
The product of 5*2*4*4*4 = 640 and product = 640
The product of 5*2*4*8*2 = 640 and product = 640
The product of 5*2*8*1*8 = 640 and product = 640
The product of 5*2*8*2*4 = 640 and product = 640
The product of 5*2*8*4*2 = 640 and product = 640
The product of 5*2*8*8*1 = 640 and product = 640
The product of 5*4*1*4*8 = 640 and product = 640
The product of 5*4*1*8*4 = 640 and product = 640
The product of 5*4*2*2*8 = 640 and product = 640
The product of 5*4*2*4*4 = 640 and product = 640
The product of 5*4*2*8*2 = 640 and product = 640
The product of 5*4*4*1*8 = 640 and product = 640
The product of 5*4*4*2*4 = 640 and product = 640
The product of 5*4*4*4*2 = 640 and product = 640
The product of 5*4*4*8*1 = 640 and product = 640
The product of 5*4*8*1*4 = 640 and product = 640
The product of 5*4*8*2*2 = 640 and product = 640
The product of 5*4*8*4*1 = 640 and product = 640
The product of 5*8*1*2*8 = 640 and product = 640
The product of 5*8*1*4*4 = 640 and product = 640
The product of 5*8*1*8*2 = 640 and product = 640
The product of 5*8*2*1*8 = 640 and product = 640
The product of 5*8*2*2*4 = 640 and product = 640
The product of 5*8*2*4*2 = 640 and product = 640
The product of 5*8*2*8*1 = 640 and product = 640
The product of 5*8*4*1*4 = 640 and product = 640
The product of 5*8*4*2*2 = 640 and product = 640
The product of 5*8*4*4*1 = 640 and product = 640
The product of 5*8*8*1*2 = 640 and product = 640
The product of 5*8*8*2*1 = 640 and product = 640
The product of 8*1*2*5*8 = 640 and product = 640
The product of 8*1*2*8*5 = 640 and product = 640
The product of 8*1*4*4*5 = 640 and product = 640
The product of 8*1*4*5*4 = 640 and product = 640
The product of 8*1*5*2*8 = 640 and product = 640
The product of 8*1*5*4*4 = 640 and product = 640
The product of 8*1*5*8*2 = 640 and product = 640
The product of 8*1*8*2*5 = 640 and product = 640
The product of 8*1*8*5*2 = 640 and product = 640
The product of 8*2*1*5*8 = 640 and product = 640
The product of 8*2*1*8*5 = 640 and product = 640
The product of 8*2*2*4*5 = 640 and product = 640
The product of 8*2*2*5*4 = 640 and product = 640
The product of 8*2*4*2*5 = 640 and product = 640
The product of 8*2*4*5*2 = 640 and product = 640
The product of 8*2*5*1*8 = 640 and product = 640
The product of 8*2*5*2*4 = 640 and product = 640
The product of 8*2*5*4*2 = 640 and product = 640
The product of 8*2*5*8*1 = 640 and product = 640
The product of 8*2*8*1*5 = 640 and product = 640
The product of 8*2*8*5*1 = 640 and product = 640
The product of 8*4*1*4*5 = 640 and product = 640
The product of 8*4*1*5*4 = 640 and product = 640
The product of 8*4*2*2*5 = 640 and product = 640
The product of 8*4*2*5*2 = 640 and product = 640
The product of 8*4*4*1*5 = 640 and product = 640
The product of 8*4*4*5*1 = 640 and product = 640
The product of 8*4*5*1*4 = 640 and product = 640
The product of 8*4*5*2*2 = 640 and product = 640
The product of 8*4*5*4*1 = 640 and product = 640
The product of 8*5*1*2*8 = 640 and product = 640
The product of 8*5*1*4*4 = 640 and product = 640
The product of 8*5*1*8*2 = 640 and product = 640
The product of 8*5*2*1*8 = 640 and product = 640
The product of 8*5*2*2*4 = 640 and product = 640
The product of 8*5*2*4*2 = 640 and product = 640
The product of 8*5*2*8*1 = 640 and product = 640
The product of 8*5*4*1*4 = 640 and product = 640
The product of 8*5*4*2*2 = 640 and product = 640
The product of 8*5*4*4*1 = 640 and product = 640
The product of 8*5*8*1*2 = 640 and product = 640
The product of 8*5*8*2*1 = 640 and product = 640
The product of 8*8*1*2*5 = 640 and product = 640
The product of 8*8*1*5*2 = 640 and product = 640
The product of 8*8*2*1*5 = 640 and product = 640
The product of 8*8*2*5*1 = 640 and product = 640
The product of 8*8*5*1*2 = 640 and product = 640
The product of 8*8*5*2*1 = 640 and product = 640

   a  b  c  d  e  product     p
0  3  5  5  5  8     3000  3000
1  3  5  5  8  5     3000  3000
2  3  5  8  5  5     3000  3000
3  3  8  5  5  5     3000  3000
4  4  5  5  5  6     3000  3000

In [6]:
# Find which numbers make the vertical products evaluate to a non-integer

qdict = []

for p in products:
    for l in range(1,10):
        quotient = p/l
        if not int(quotient) == quotient and isinstance(quotient, float):
            print("The quotient of {}/{} = {} and dividend = {}".format(p, l, quotient, p))
            q = {'dividend':p, 'divisor':l, 'quotient':quotient, 'p':p}
            qdict.append(q)
            
qdf = pd.DataFrame(qdict, columns=['dividend', 'divisor','quotient','p'])
qdf.head()

# Middle column cannot have 3, 6, 9 and right-most column cannot have 4, 5, 8

The quotient of 3000/7 = 428.57142857142856 and dividend = 3000
The quotient of 3000/9 = 333.3333333333333 and dividend = 3000
The quotient of 3969/2 = 1984.5 and dividend = 3969
The quotient of 3969/4 = 992.25 and dividend = 3969
The quotient of 3969/5 = 793.8 and dividend = 3969
The quotient of 3969/6 = 661.5 and dividend = 3969
The quotient of 3969/8 = 496.125 and dividend = 3969
The quotient of 640/3 = 213.33333333333334 and dividend = 640
The quotient of 640/6 = 106.66666666666667 and dividend = 640
The quotient of 640/7 = 91.42857142857143 and dividend = 640
The quotient of 640/9 = 71.11111111111111 and dividend = 640

   dividend  divisor     quotient     p
0      3000        7   428.571429  3000
1      3000        9   333.333333  3000
2      3969        2  1984.500000  3969
3      3969        4   992.250000  3969
4      3969        5   793.800000  3969

In [32]:
vdf.head()

   a  b  c  e  f  g  h  product        p
0  5  7  7  8  8  9  9  8890560  8890560
1  5  7  7  8  9  8  9  8890560  8890560
2  5  7  7  8  9  9  8  8890560  8890560
3  5  7  7  9  8  8  9  8890560  8890560
4  5  7  7  9  8  9  8  8890560  8890560

In [9]:
# Remove those rows from hdf

hdf2 = hdf.loc[~(hdf.i.isin([7,9])&hdf.j.isin([2,4,5,6,8])&hdf.k.isin([3,6,7,9]))]
print("Horizontal combinations decreased from {} to {}".format(str(len(hdf)),str(len(hdf2))))

Horizontal combinations decreased from 37 to 36

In [10]:
columns = ['a','b','c','d','e']

rows = 0

for c in columns:
    # print(c)
    temp = vdf.loc[(vdf['product'] == 3000) & (vdf[c].isin([7,9]))]
    rows += len(temp)
    if len(temp) > 0:
        vdf = vdf.loc[~((vdf['product'] == 3000) & (vdf[c].isin([7,9])))]
        
for c in columns:
    # print(c)
    temp = vdf.loc[(vdf['product'] == 3969) & (vdf[c].isin([2,4,5,6,8]))]
    rows += len(temp)
    if len(temp) > 0:
        vdf = vdf.loc[~((vdf['product'] == 3969) & (vdf[c].isin([2,4,5,6,8])))]

for c in columns:
    # print(c)
    temp = vdf.loc[(vdf['product'] == 640) & (vdf[c].isin([3,6,7,9]))]
    rows += len(temp)
    if len(temp) > 0:
        vdf = vdf.loc[~((vdf['product'] == 640) & (vdf[c].isin([3,6,7,9])))]

In [11]:
# Get each row from horizontal dataframe as tuple, add it to dictionary of lists of tuples

hdfdict = {}

for h in hdf.p.unique():
    temp = hdf.loc[(hdf['product'] == h)][['i','j','k']]
    temptuple = [tuple(r) for r in temp.to_numpy()]
    hdfdict[h] = temptuple
    
print(hdfdict)

{135: [(3, 5, 9), (3, 9, 5), (5, 3, 9), (5, 9, 3), (9, 3, 5), (9, 5, 3)], 45: [(1, 5, 9), (1, 9, 5), (3, 3, 5), (3, 5, 3), (5, 1, 9), (5, 3, 3), (5, 9, 1), (9, 1, 5), (9, 5, 1)], 64: [(1, 8, 8), (2, 4, 8), (2, 8, 4), (4, 2, 8), (4, 4, 4), (4, 8, 2), (8, 1, 8), (8, 2, 4), (8, 4, 2), (8, 8, 1)], 280: [(5, 7, 8), (5, 8, 7), (7, 5, 8), (7, 8, 5), (8, 5, 7), (8, 7, 5)], 70: [(2, 5, 7), (2, 7, 5), (5, 2, 7), (5, 7, 2), (7, 2, 5), (7, 5, 2)]}