In [2]:
import pandas as pd

products = [1458, 128, 2688, 125]

hdict = []

for p in products:
    for i in range(10):
        for j in range(10):
            for k in range(10):
                for l in range(10):
                    product = i*j*k*l
                    # print("The product of {}*{}*{}*{} = {}".format(i, j, k, l, product))
                    if product == p:
                        print("The product of {}*{}*{}*{} = {} and product = {}".format(i, j, k, l, product, p))
                        h = {'i':i, 'j':j, 'k':k, 'l':l, 'product':product, 'p':p}
                        hdict.append(h)

hdf = pd.DataFrame(hdict, columns=['i','j','k','l','product','p'])
hdf.head()

The product of 2*9*9*9 = 1458 and product = 1458
The product of 3*6*9*9 = 1458 and product = 1458
The product of 3*9*6*9 = 1458 and product = 1458
The product of 3*9*9*6 = 1458 and product = 1458
The product of 6*3*9*9 = 1458 and product = 1458
The product of 6*9*3*9 = 1458 and product = 1458
The product of 6*9*9*3 = 1458 and product = 1458
The product of 9*2*9*9 = 1458 and product = 1458
The product of 9*3*6*9 = 1458 and product = 1458
The product of 9*3*9*6 = 1458 and product = 1458
The product of 9*6*3*9 = 1458 and product = 1458
The product of 9*6*9*3 = 1458 and product = 1458
The product of 9*9*2*9 = 1458 and product = 1458
The product of 9*9*3*6 = 1458 and product = 1458
The product of 9*9*6*3 = 1458 and product = 1458
The product of 9*9*9*2 = 1458 and product = 1458
The product of 1*2*8*8 = 128 and product = 128
The product of 1*4*4*8 = 128 and product = 128
The product of 1*4*8*4 = 128 and product = 128
The product of 1*8*2*8 = 128 and product = 128
The product of 1*8*4*4 = 128 and product = 128
The product of 1*8*8*2 = 128 and product = 128
The product of 2*1*8*8 = 128 and product = 128
The product of 2*2*4*8 = 128 and product = 128
The product of 2*2*8*4 = 128 and product = 128
The product of 2*4*2*8 = 128 and product = 128
The product of 2*4*4*4 = 128 and product = 128
The product of 2*4*8*2 = 128 and product = 128
The product of 2*8*1*8 = 128 and product = 128
The product of 2*8*2*4 = 128 and product = 128
The product of 2*8*4*2 = 128 and product = 128
The product of 2*8*8*1 = 128 and product = 128
The product of 4*1*4*8 = 128 and product = 128
The product of 4*1*8*4 = 128 and product = 128
The product of 4*2*2*8 = 128 and product = 128
The product of 4*2*4*4 = 128 and product = 128
The product of 4*2*8*2 = 128 and product = 128
The product of 4*4*1*8 = 128 and product = 128
The product of 4*4*2*4 = 128 and product = 128
The product of 4*4*4*2 = 128 and product = 128
The product of 4*4*8*1 = 128 and product = 128
The product of 4*8*1*4 = 128 and product = 128
The product of 4*8*2*2 = 128 and product = 128
The product of 4*8*4*1 = 128 and product = 128
The product of 8*1*2*8 = 128 and product = 128
The product of 8*1*4*4 = 128 and product = 128
The product of 8*1*8*2 = 128 and product = 128
The product of 8*2*1*8 = 128 and product = 128
The product of 8*2*2*4 = 128 and product = 128
The product of 8*2*4*2 = 128 and product = 128
The product of 8*2*8*1 = 128 and product = 128
The product of 8*4*1*4 = 128 and product = 128
The product of 8*4*2*2 = 128 and product = 128
The product of 8*4*4*1 = 128 and product = 128
The product of 8*8*1*2 = 128 and product = 128
The product of 8*8*2*1 = 128 and product = 128
The product of 6*7*8*8 = 2688 and product = 2688
The product of 6*8*7*8 = 2688 and product = 2688
The product of 6*8*8*7 = 2688 and product = 2688
The product of 7*6*8*8 = 2688 and product = 2688
The product of 7*8*6*8 = 2688 and product = 2688
The product of 7*8*8*6 = 2688 and product = 2688
The product of 8*6*7*8 = 2688 and product = 2688
The product of 8*6*8*7 = 2688 and product = 2688
The product of 8*7*6*8 = 2688 and product = 2688
The product of 8*7*8*6 = 2688 and product = 2688
The product of 8*8*6*7 = 2688 and product = 2688
The product of 8*8*7*6 = 2688 and product = 2688
The product of 1*5*5*5 = 125 and product = 125
The product of 5*1*5*5 = 125 and product = 125
The product of 5*5*1*5 = 125 and product = 125
The product of 5*5*5*1 = 125 and product = 125

   i  j  k  l  product     p
0  2  9  9  9     1458  1458
1  3  6  9  9     1458  1458
2  3  9  6  9     1458  1458
3  3  9  9  6     1458  1458
4  6  3  9  9     1458  1458

In [3]:
products = [960, 384, 630, 270]

vdict = []

for p in products:
    for a in range(10):
        for b in range(10):
            for c in range(10):
                for d in range(10):
                    product = a*b*c*d
                    # print("The product of {}*{}*{} = {}".format(i, j, k, product))
                    if product == p:
                        solution = "{}*{}*{}*{}".format(a, b, c, d)
                        print("The product of {}*{}*{}*{} = {} and product = {}".format(a, b, c, d, product, p))
                        v = {'a':a, 'b':b, 'c':c, 'd':d, 'product':product, 'p':p}
                        vdict.append(v)

vdf = pd.DataFrame(vdict, columns=['a','b','c','d','product','p'])
vdf.head()

The product of 3*5*8*8 = 960 and product = 960
The product of 3*8*5*8 = 960 and product = 960
The product of 3*8*8*5 = 960 and product = 960
The product of 4*5*6*8 = 960 and product = 960
The product of 4*5*8*6 = 960 and product = 960
The product of 4*6*5*8 = 960 and product = 960
The product of 4*6*8*5 = 960 and product = 960
The product of 4*8*5*6 = 960 and product = 960
The product of 4*8*6*5 = 960 and product = 960
The product of 5*3*8*8 = 960 and product = 960
The product of 5*4*6*8 = 960 and product = 960
The product of 5*4*8*6 = 960 and product = 960
The product of 5*6*4*8 = 960 and product = 960
The product of 5*6*8*4 = 960 and product = 960
The product of 5*8*3*8 = 960 and product = 960
The product of 5*8*4*6 = 960 and product = 960
The product of 5*8*6*4 = 960 and product = 960
The product of 5*8*8*3 = 960 and product = 960
The product of 6*4*5*8 = 960 and product = 960
The product of 6*4*8*5 = 960 and product = 960
The product of 6*5*4*8 = 960 and product = 960
The product of 6*5*8*4 = 960 and product = 960
The product of 6*8*4*5 = 960 and product = 960
The product of 6*8*5*4 = 960 and product = 960
The product of 8*3*5*8 = 960 and product = 960
The product of 8*3*8*5 = 960 and product = 960
The product of 8*4*5*6 = 960 and product = 960
The product of 8*4*6*5 = 960 and product = 960
The product of 8*5*3*8 = 960 and product = 960
The product of 8*5*4*6 = 960 and product = 960
The product of 8*5*6*4 = 960 and product = 960
The product of 8*5*8*3 = 960 and product = 960
The product of 8*6*4*5 = 960 and product = 960
The product of 8*6*5*4 = 960 and product = 960
The product of 8*8*3*5 = 960 and product = 960
The product of 8*8*5*3 = 960 and product = 960
The product of 1*6*8*8 = 384 and product = 384
The product of 1*8*6*8 = 384 and product = 384
The product of 1*8*8*6 = 384 and product = 384
The product of 2*3*8*8 = 384 and product = 384
The product of 2*4*6*8 = 384 and product = 384
The product of 2*4*8*6 = 384 and product = 384
The product of 2*6*4*8 = 384 and product = 384
The product of 2*6*8*4 = 384 and product = 384
The product of 2*8*3*8 = 384 and product = 384
The product of 2*8*4*6 = 384 and product = 384
The product of 2*8*6*4 = 384 and product = 384
The product of 2*8*8*3 = 384 and product = 384
The product of 3*2*8*8 = 384 and product = 384
The product of 3*4*4*8 = 384 and product = 384
The product of 3*4*8*4 = 384 and product = 384
The product of 3*8*2*8 = 384 and product = 384
The product of 3*8*4*4 = 384 and product = 384
The product of 3*8*8*2 = 384 and product = 384
The product of 4*2*6*8 = 384 and product = 384
The product of 4*2*8*6 = 384 and product = 384
The product of 4*3*4*8 = 384 and product = 384
The product of 4*3*8*4 = 384 and product = 384
The product of 4*4*3*8 = 384 and product = 384
The product of 4*4*4*6 = 384 and product = 384
The product of 4*4*6*4 = 384 and product = 384
The product of 4*4*8*3 = 384 and product = 384
The product of 4*6*2*8 = 384 and product = 384
The product of 4*6*4*4 = 384 and product = 384
The product of 4*6*8*2 = 384 and product = 384
The product of 4*8*2*6 = 384 and product = 384
The product of 4*8*3*4 = 384 and product = 384
The product of 4*8*4*3 = 384 and product = 384
The product of 4*8*6*2 = 384 and product = 384
The product of 6*1*8*8 = 384 and product = 384
The product of 6*2*4*8 = 384 and product = 384
The product of 6*2*8*4 = 384 and product = 384
The product of 6*4*2*8 = 384 and product = 384
The product of 6*4*4*4 = 384 and product = 384
The product of 6*4*8*2 = 384 and product = 384
The product of 6*8*1*8 = 384 and product = 384
The product of 6*8*2*4 = 384 and product = 384
The product of 6*8*4*2 = 384 and product = 384
The product of 6*8*8*1 = 384 and product = 384
The product of 8*1*6*8 = 384 and product = 384
The product of 8*1*8*6 = 384 and product = 384
The product of 8*2*3*8 = 384 and product = 384
The product of 8*2*4*6 = 384 and product = 384
The product of 8*2*6*4 = 384 and product = 384
The product of 8*2*8*3 = 384 and product = 384
The product of 8*3*2*8 = 384 and product = 384
The product of 8*3*4*4 = 384 and product = 384
The product of 8*3*8*2 = 384 and product = 384
The product of 8*4*2*6 = 384 and product = 384
The product of 8*4*3*4 = 384 and product = 384
The product of 8*4*4*3 = 384 and product = 384
The product of 8*4*6*2 = 384 and product = 384
The product of 8*6*1*8 = 384 and product = 384
The product of 8*6*2*4 = 384 and product = 384
The product of 8*6*4*2 = 384 and product = 384
The product of 8*6*8*1 = 384 and product = 384
The product of 8*8*1*6 = 384 and product = 384
The product of 8*8*2*3 = 384 and product = 384
The product of 8*8*3*2 = 384 and product = 384
The product of 8*8*6*1 = 384 and product = 384
The product of 2*5*7*9 = 630 and product = 630
The product of 2*5*9*7 = 630 and product = 630
The product of 2*7*5*9 = 630 and product = 630
The product of 2*7*9*5 = 630 and product = 630
The product of 2*9*5*7 = 630 and product = 630
The product of 2*9*7*5 = 630 and product = 630
The product of 3*5*6*7 = 630 and product = 630
The product of 3*5*7*6 = 630 and product = 630
The product of 3*6*5*7 = 630 and product = 630
The product of 3*6*7*5 = 630 and product = 630
The product of 3*7*5*6 = 630 and product = 630
The product of 3*7*6*5 = 630 and product = 630
The product of 5*2*7*9 = 630 and product = 630
The product of 5*2*9*7 = 630 and product = 630
The product of 5*3*6*7 = 630 and product = 630
The product of 5*3*7*6 = 630 and product = 630
The product of 5*6*3*7 = 630 and product = 630
The product of 5*6*7*3 = 630 and product = 630
The product of 5*7*2*9 = 630 and product = 630
The product of 5*7*3*6 = 630 and product = 630
The product of 5*7*6*3 = 630 and product = 630
The product of 5*7*9*2 = 630 and product = 630
The product of 5*9*2*7 = 630 and product = 630
The product of 5*9*7*2 = 630 and product = 630
The product of 6*3*5*7 = 630 and product = 630
The product of 6*3*7*5 = 630 and product = 630
The product of 6*5*3*7 = 630 and product = 630
The product of 6*5*7*3 = 630 and product = 630
The product of 6*7*3*5 = 630 and product = 630
The product of 6*7*5*3 = 630 and product = 630
The product of 7*2*5*9 = 630 and product = 630
The product of 7*2*9*5 = 630 and product = 630
The product of 7*3*5*6 = 630 and product = 630
The product of 7*3*6*5 = 630 and product = 630
The product of 7*5*2*9 = 630 and product = 630
The product of 7*5*3*6 = 630 and product = 630
The product of 7*5*6*3 = 630 and product = 630
The product of 7*5*9*2 = 630 and product = 630
The product of 7*6*3*5 = 630 and product = 630
The product of 7*6*5*3 = 630 and product = 630
The product of 7*9*2*5 = 630 and product = 630
The product of 7*9*5*2 = 630 and product = 630
The product of 9*2*5*7 = 630 and product = 630
The product of 9*2*7*5 = 630 and product = 630
The product of 9*5*2*7 = 630 and product = 630
The product of 9*5*7*2 = 630 and product = 630
The product of 9*7*2*5 = 630 and product = 630
The product of 9*7*5*2 = 630 and product = 630
The product of 1*5*6*9 = 270 and product = 270
The product of 1*5*9*6 = 270 and product = 270
The product of 1*6*5*9 = 270 and product = 270
The product of 1*6*9*5 = 270 and product = 270
The product of 1*9*5*6 = 270 and product = 270
The product of 1*9*6*5 = 270 and product = 270
The product of 2*3*5*9 = 270 and product = 270
The product of 2*3*9*5 = 270 and product = 270
The product of 2*5*3*9 = 270 and product = 270
The product of 2*5*9*3 = 270 and product = 270
The product of 2*9*3*5 = 270 and product = 270
The product of 2*9*5*3 = 270 and product = 270
The product of 3*2*5*9 = 270 and product = 270
The product of 3*2*9*5 = 270 and product = 270
The product of 3*3*5*6 = 270 and product = 270
The product of 3*3*6*5 = 270 and product = 270
The product of 3*5*2*9 = 270 and product = 270
The product of 3*5*3*6 = 270 and product = 270
The product of 3*5*6*3 = 270 and product = 270
The product of 3*5*9*2 = 270 and product = 270
The product of 3*6*3*5 = 270 and product = 270
The product of 3*6*5*3 = 270 and product = 270
The product of 3*9*2*5 = 270 and product = 270
The product of 3*9*5*2 = 270 and product = 270
The product of 5*1*6*9 = 270 and product = 270
The product of 5*1*9*6 = 270 and product = 270
The product of 5*2*3*9 = 270 and product = 270
The product of 5*2*9*3 = 270 and product = 270
The product of 5*3*2*9 = 270 and product = 270
The product of 5*3*3*6 = 270 and product = 270
The product of 5*3*6*3 = 270 and product = 270
The product of 5*3*9*2 = 270 and product = 270
The product of 5*6*1*9 = 270 and product = 270
The product of 5*6*3*3 = 270 and product = 270
The product of 5*6*9*1 = 270 and product = 270
The product of 5*9*1*6 = 270 and product = 270
The product of 5*9*2*3 = 270 and product = 270
The product of 5*9*3*2 = 270 and product = 270
The product of 5*9*6*1 = 270 and product = 270
The product of 6*1*5*9 = 270 and product = 270
The product of 6*1*9*5 = 270 and product = 270
The product of 6*3*3*5 = 270 and product = 270
The product of 6*3*5*3 = 270 and product = 270
The product of 6*5*1*9 = 270 and product = 270
The product of 6*5*3*3 = 270 and product = 270
The product of 6*5*9*1 = 270 and product = 270
The product of 6*9*1*5 = 270 and product = 270
The product of 6*9*5*1 = 270 and product = 270
The product of 9*1*5*6 = 270 and product = 270
The product of 9*1*6*5 = 270 and product = 270
The product of 9*2*3*5 = 270 and product = 270
The product of 9*2*5*3 = 270 and product = 270
The product of 9*3*2*5 = 270 and product = 270
The product of 9*3*5*2 = 270 and product = 270
The product of 9*5*1*6 = 270 and product = 270
The product of 9*5*2*3 = 270 and product = 270
The product of 9*5*3*2 = 270 and product = 270
The product of 9*5*6*1 = 270 and product = 270
The product of 9*6*1*5 = 270 and product = 270
The product of 9*6*5*1 = 270 and product = 270

   a  b  c  d  product    p
0  3  5  8  8      960  960
1  3  8  5  8      960  960
2  3  8  8  5      960  960
3  4  5  6  8      960  960
4  4  5  8  6      960  960

In [5]:
# Find which numbers make the vertical products evaluate to a non-integer

qdict = []

for p in products:
    for l in range(1,10):
        quotient = p/l
        if not int(quotient) == quotient and isinstance(quotient, float):
            print("The quotient of {}/{} = {} and dividend = {}".format(p, l, quotient, p))
            q = {'dividend':p, 'divisor':l, 'quotient':quotient, 'p':p}
            qdict.append(q)
            
qdf = pd.DataFrame(qdict, columns=['dividend', 'divisor','quotient','p'])
qdf.head()

# Middle column cannot have 3, 6, 9 and right-most column cannot have 4, 5, 8

The quotient of 960/7 = 137.14285714285714 and dividend = 960
The quotient of 960/9 = 106.66666666666667 and dividend = 960
The quotient of 384/5 = 76.8 and dividend = 384
The quotient of 384/7 = 54.857142857142854 and dividend = 384
The quotient of 384/9 = 42.666666666666664 and dividend = 384
The quotient of 630/4 = 157.5 and dividend = 630
The quotient of 630/8 = 78.75 and dividend = 630
The quotient of 270/4 = 67.5 and dividend = 270
The quotient of 270/7 = 38.57142857142857 and dividend = 270
The quotient of 270/8 = 33.75 and dividend = 270

   dividend  divisor    quotient    p
0       960        7  137.142857  960
1       960        9  106.666667  960
2       384        5   76.800000  384
3       384        7   54.857143  384
4       384        9   42.666667  384

In [6]:
vdf.head()

   a  b  c  d  product    p
0  3  5  8  8      960  960
1  3  8  5  8      960  960
2  3  8  8  5      960  960
3  4  5  6  8      960  960
4  4  5  8  6      960  960

In [7]:
# Remove those rows from hdf

hdf2 = hdf.loc[~(hdf.i.isin([7,9])&hdf.j.isin([5,7,9])&hdf.k.isin([4,8])&hdf.l.isin([4,7,8]))]
print("Horizontal combinations decreased from {} to {}".format(str(len(hdf)),str(len(hdf2))))

Horizontal combinations decreased from 72 to 72

In [8]:
columns = ['a','b','c','d']

rows = 0

for c in columns:
    # print(c)
    temp = vdf.loc[(vdf['product'] == 960) & (vdf[c].isin([7,9]))]
    rows += len(temp)
    if len(temp) > 0:
        vdf = vdf.loc[~((vdf['product'] == 960) & (vdf[c].isin([7,9])))]

for c in columns:
    # print(c)
    temp = vdf.loc[(vdf['product'] == 384) & (vdf[c].isin([5,7,9]))]
    rows += len(temp)
    if len(temp) > 0:
        vdf = vdf.loc[~((vdf['product'] == 384) & (vdf[c].isin([5,7,9])))]
        
for c in columns:
    # print(c)
    temp = vdf.loc[(vdf['product'] == 630) & (vdf[c].isin([4,8]))]
    rows += len(temp)
    if len(temp) > 0:
        vdf = vdf.loc[~((vdf['product'] == 630) & (vdf[c].isin([4,8])))]

for c in columns:
    # print(c)
    temp = vdf.loc[(vdf['product'] == 270) & (vdf[c].isin([4,7,8]))]
    rows += len(temp)
    if len(temp) > 0:
        vdf = vdf.loc[~((vdf['product'] == 270) & (vdf[c].isin([4,7,8])))]

In [9]:
# Get each row from horizontal dataframe as tuple, add it to dictionary of lists of tuples

hdfdict = {}

for h in hdf.p.unique():
    temp = hdf.loc[(hdf['product'] == h)][['i','j','k','l']]
    temptuple = [tuple(r) for r in temp.to_numpy()]
    hdfdict[h] = temptuple
    
print(hdfdict)

{1458: [(2, 9, 9, 9), (3, 6, 9, 9), (3, 9, 6, 9), (3, 9, 9, 6), (6, 3, 9, 9), (6, 9, 3, 9), (6, 9, 9, 3), (9, 2, 9, 9), (9, 3, 6, 9), (9, 3, 9, 6), (9, 6, 3, 9), (9, 6, 9, 3), (9, 9, 2, 9), (9, 9, 3, 6), (9, 9, 6, 3), (9, 9, 9, 2)], 128: [(1, 2, 8, 8), (1, 4, 4, 8), (1, 4, 8, 4), (1, 8, 2, 8), (1, 8, 4, 4), (1, 8, 8, 2), (2, 1, 8, 8), (2, 2, 4, 8), (2, 2, 8, 4), (2, 4, 2, 8), (2, 4, 4, 4), (2, 4, 8, 2), (2, 8, 1, 8), (2, 8, 2, 4), (2, 8, 4, 2), (2, 8, 8, 1), (4, 1, 4, 8), (4, 1, 8, 4), (4, 2, 2, 8), (4, 2, 4, 4), (4, 2, 8, 2), (4, 4, 1, 8), (4, 4, 2, 4), (4, 4, 4, 2), (4, 4, 8, 1), (4, 8, 1, 4), (4, 8, 2, 2), (4, 8, 4, 1), (8, 1, 2, 8), (8, 1, 4, 4), (8, 1, 8, 2), (8, 2, 1, 8), (8, 2, 2, 4), (8, 2, 4, 2), (8, 2, 8, 1), (8, 4, 1, 4), (8, 4, 2, 2), (8, 4, 4, 1), (8, 8, 1, 2), (8, 8, 2, 1)], 2688: [(6, 7, 8, 8), (6, 8, 7, 8), (6, 8, 8, 7), (7, 6, 8, 8), (7, 8, 6, 8), (7, 8, 8, 6), (8, 6, 7, 8), (8, 6, 8, 7), (8, 7, 6, 8), (8, 7, 8, 6), (8, 8, 6, 7), (8, 8, 7, 6)], 125: [(1, 5, 5, 5), (5, 1, 5, 5), (5, 5, 1, 5), (5, 5, 5, 1)]}

In [10]:
# Rules
a = [7,9]
b = [5,7,9]
c = [4,8]
d = [4,7,8]

hdfdictres = {}

for k, v in hdfdict.items():
    tl = []
    for t in v:
        if t[0] not in a and t[1] not in b and t[2] not in c and t[3] not in d:
            tl.append(t)
            # print('Potential solution found.')
    hdfdictres[k] = tl

In [11]:
hdfdictres

{1458: [(3, 6, 9, 9), (6, 3, 9, 9)],
 128: [(4, 8, 2, 2), (8, 4, 2, 2), (8, 8, 1, 2), (8, 8, 2, 1)],
 2688: [(8, 8, 7, 6)],
 125: [(5, 1, 5, 5)]}